''''''''''''''''''Begining PLANTUML params'''''''''''''''''
@startuml
hide footbox
skinparam monochrome true
skinparam sequenceMessageAlign center

participant ParentPlayer
participant ParentPM
participant ParentCM
participant ChildPM
participant ChildCM
participant ChildPlayer

''''''''''''''''''Paper - Control Propertys of media object in active Sequence'''''''''''''''''
title Paper - Control Propertys of media object in active Sequence
activate ParentPlayer
activate ParentCM
activate ChildCM
activate ChildPlayer
== setPropertyValue ==
ParentPlayer->ParentCM: setPropertyValue("height","50%","1s","m1ID")
ParentCM->ChildCM: setPropertyValue("height","50%","1s","m1ID")
ChildCM->ChildPlayer: setPropertyValue("height","50%","1s")
== requestPropertyValue/reportPropertyValue ==
ParentPlayer->ParentCM: requestPropertyValue("top","m1ID")
ParentCM->ChildCM: requestPropertyValue("top","m1ID")
ChildCM->ChildPlayer: requestPropertyValue("top")
ChildPlayer->ChildCM: reportPropertyValue("top","30%")
ChildCM->ParentCM: reportPropertyValue("top","30%","m1ID")
ParentCM->ParentPlayer: reportPropertyValue("top","30%")

''''''''''''''''''Ending PLANTUML params'''''''''''''''''
@enduml