'====================Begining PLANTUML params====================
@startuml
hide footbox
skinparam monochrome true
skinparam sequenceMessageAlign center

participant ParentHPE
participant ParentPM
participant ParentCM
participant ChildPM
participant ChildCM
participant ChildHPE

'====================Propose - Set Variable Sequence====================
title Propose - Set Variable Sequence
activate ParentHPE
activate ParentPM
activate ChildPM
ParentHPE->ParentPM: setClassVariableValue("class(5).device(1).var1","value")
ParentPM->ChildPM: setClassVariableValue("class(5).device(1).var1","value")
activate ChildHPE
ChildPM->ChildHPE: setClassVariableValue("class(5).device(1).var1","value")
ChildHPE->ChildPM: requestClassVariableValue("class(5).device(1).var2","value")
ChildPM->ParentPM: requestClassVariableValue("class(5).device(1).var2","value")
ParentPM->ParentHPE: requestClassVariableValue("class(5).device(1).var2","value")
ParentHPE->ParentPM: notifyClassVariableValue("class(5).device(1).var2","value")
ParentPM->ChildPM: notifyClassVariableValue("class(5).device(1).var2","value")
ChildPM->ChildHPE: notifyClassVariableValue("class(5).device(1).var2","value")

'====================Ending PLANTUML params====================
@enduml