''''''''''''''''''Begining PLANTUML params'''''''''''''''''
@startuml
hide footbox
skinparam monochrome true
skinparam sequenceMessageAlign center

participant ParentPlayer
participant ParentPM
participant ParentCM
participant ChildPM
participant ChildCM
participant ChildPlayer

''''''''''''''''''Proposal - Control Propertys of media object in active Sequence'''''''''''''''''
title Proposal - Control Propertys of media object in active Sequence
activate ParentPlayer
activate ParentCM
activate ChildCM
activate ChildPlayer
== setPropertyValue ==
ParentPlayer->ParentCM: setPropertyValue("m1ID","height","50%", "1s")
ParentCM->ChildCM: setPropertyValue("m1ID","height","50%", "1s")
ChildCM->ChildPlayer: setPropertyValue("height","50%", "1s")
== requestPropertyValue/reportPropertyValue ==
ParentPlayer->ParentCM: requestPropertyValue("m1ID","top")
ParentCM->ChildCM: requestPropertyValue("m1ID,"top")
ChildCM->ChildPlayer: requestPropertyValue("top")
ChildPlayer->ChildCM: reportPropertyValue("m1ID,"top","30%")
ChildCM->ParentCM: reportPropertyValue("m1ID,"top","30%")
ParentCM->ParentPlayer: reportPropertyValue("m1ID,"top")

''''''''''''''''''Ending PLANTUML params'''''''''''''''''
@enduml