'====================================================================PAPER====================================================================================================
'title Paper - Paring Sequence
'PPM->CPM: classAnnouncement(2, "garrincha","RDF>","Garrincha aplication")
'CPM->PPM: addDeviceToClass(2, "garrincha", "<RDF>")
'CPM->+PPM: getChildIndex(2, "garrincha", "<RDF>")
'PPM->-CPM: return("value")
'
'title Paper - Handling classes variables Sequence
'HPE->PPM: setClassVariableValue("class(2).device(1).var1", "value" 
'PPM->CPM: setClassVariableValue("class(2).device(1).var1", "value" 
'CPM->HPE2: setClassVariableValue("class(2).device(1).var1", "value" 
'HPE->+PPM: getClassVariableValue("class(2).device(1).var2", "value" 
'PPM->+HPE2: getClassVariableValue("class(2).device(1).var2", "value" 
'HPE2->-PPM: return("value")
'PPM->-HPE: return("value")
'
'title Paper - Control Events of media object in active active Sequence
'HPE->PCM: prepare({("height","10%"), ("top","30%")}, {("evt1", "selection of a media", "selection"), ("evt2", "presentation of a media", "presentation")}, "file://video.mp4", "m1" )
'HPE->PCM: addEvent(("evt3", "atribution of a segment of a media", "atribution"), "m1" )
'HPE->PCM: removeEvent(("evt1", "m1" )
'HPE>PCM: postAction("start", "evt1", "m1" )
'PCM->HPE: notifyEventTransition(""", "begins","m1" )
'
'title Paper - Control Propertys of media object in active active Sequence
'HPE->PCM: setPropertyValue(("height", "50%", 0, "m1" )
'HPE->PCM: requestPropertyValue("top", "m1" )
'PCM->HPE: reportPropertyValue("top", "30%","m1")
'
'=================================================================PROPOSE=======================================================================================================
'title Paring Sequence
'PPM->CPM: classAnnouncement(2, "garrincha","<RDF>","Garrincha aplication")
'CPM->PPM: addDeviceToClass(2, "garrincha", "<RDF>")
'CPM->PPM: setChildIndex(2, "garrincha", "<RDF>")
'
'title Set Variable Sequence
'PPM->HPE: setClassVariableValue("class(2).device(1).var1", "value")
'PPM->HPE: requestClassVariableValue("class(2).device(1).var2", "value" 
'HPE->PPM: notifyClassVariableValue("class(2).device(1).var2", "value")
'
'title Control Events of media object in active active Sequence
'HPE/PCM->PCM/CCM: prepare( "m1", "file://video.mp4", {("height", "10%"), ("top", "30%")}, {("evt1", "selection of a segment of a media", "selection"), ("evt2", "presentation of a segment of a media", "presentation")})
'HPE/PCM->PCM/CCM: addEvent("m1", ("evt3", "atribution of a segment of a media", "atribution"))
'HPE/PCM->PCM/CCM: removeEvent(("m1", "evt1")
'HPE/PCM->PCM/CCM: postAction( "m1", "evt1", "start")
'PCM/CCM->HPE/PCM: notifyEventTransition("m1" , "evt1", "begins")
'
'title Control Propertys of media object in active active Sequence
'HPE/PCM->PCM/CCM: setPropertyValue(("m1" , "height", "50%", 0)
'HPE/PCM->PCM/CCM: requestPropertyValue("top", "m1" )
'PCM/CCM->HPE/PCM: notifyPropertyValue("top", "30%","m1")
'
'
'10,92cm
'8,27cm
'
'
'21,00cm
'9,79cm

