'====================Begining PLANTUML params====================
@startuml
hide footbox
skinparam monochrome true
skinparam sequenceMessageAlign center

participant ParentHPE
participant ParentPM
participant ParentCM
participant ChildPM
participant ChildCM
participant ChildHPE

'====================Paper - Paring and handling classes variables Sequence====================
title Paper - Paring Sequence
activate ParentHPE
activate ParentPM
activate ChildPM
ParentHPE->ParentHPE: Process hipermidia document
ParentHPE->ParentPM: classAnnouncement(5,"garrinchaUUID","RDF>","Garrincha App")
ParentPM->ChildPM: classAnnouncement(5,"garrinchaUUID","RDF>","Garrincha App")
ChildPM->ParentPM: addDeviceToClass(5,"garrinchaUUID","<RDF>")
ParentPM->ParentHPE: addDeviceToClass(5,"garrinchaUUID","<RDF>")
ChildPM->ParentPM: getChildIndex(5,"garrinchaUUID","<RDF>")
ParentPM->ParentHPE: getChildIndex(5,"garrinchaUUID","<RDF>")
ParentHPE-->ParentPM: return chieldIndex
ParentPM-->ChildPM: return chieldIndex

'====================Ending PLANTUML params====================
@enduml