'====================Begining PLANTUML params====================
@startuml
hide footbox
skinparam monochrome true
skinparam sequenceMessageAlign center

participant ParentHPE
participant ParentPM
participant ParentCM
participant ChildPM
participant ChildCM
participant ChildHPE

'====================Paper - Control Events of media object in active Sequence====================
title Paper - Control Events of media object in active Sequence
activate ParentHPE
activate ParentCM
ParentHPE->ParentCM: prepare( {("height","10%"), ("top","30%")},\n{("evt1ID","media selection","selection"),\n("evt2ID","media presentation","presentation")},\n"file://video.mp4",\n"m1ID" )
activate ChildCM
ParentCM->ChildCM:   prepare(..., ..., ...,"m1ID")
activate ChildHPE
ChildCM->ChildHPE:   prepare(..., ..., ...)
ParentHPE->ParentCM: addEvent(("evt3ID","media atribution","atribution"),"m1ID")
ParentCM->ChildCM:   addEvent(...,"m1ID")
ChildCM->ChildHPE:   addEvent(...)
ParentHPE->ParentCM: removeEvent(("evt1ID","m1ID")
ParentCM->ChildCM:   removeEvent(("evt1ID","m1ID")
ChildCM->ChildHPE:   removeEvent(("evt1ID","m1ID")
ParentHPE->ParentCM: postAction("start","evt2ID","m1ID")
ParentCM->ChildCM:   postAction("start","evt2ID","m1ID")
ChildCM->ChildHPE:   postAction("start","evt2ID","m1ID")
ChildHPE->ChildCM:   notifyEventTransition("evt2ID","begins","m1ID")
ChildCM->ParentCM:   notifyEventTransition("evt2ID","begins","m1ID")
ParentCM->ParentHPE: notifyEventTransition("evt2ID","begins","m1ID")

'====================Ending PLANTUML params====================
@enduml