'====================Begining PLANTUML params====================
@startuml
hide footbox
skinparam monochrome true
skinparam sequenceMessageAlign center

participant ParentHPE
participant ParentPM
participant ParentCM
participant ChildPM
participant ChildCM
participant ChildHPE

'====================Paper - Handling classes variables Sequenc''''''''''''''''
title Paper - Handling classes variables Sequence
activate ParentHPE
activate ParentPM
== setClassVariableValue ==
ParentPM->ParentHPE: setClassVariableValue("class(5).device(1).var1","value")
== getClassVariableValue ==
ParentPM->ParentHPE: getClassVariableValue("class(5).device(1).var2","value")
ParentHPE-->ParentPM: return("value")

'====================Ending PLANTUML params====================
@enduml