''''''''''''''''''Begining PLANTUML params'''''''''''''''''
@startuml
hide footbox
skinparam monochrome true
skinparam sequenceMessageAlign center

participant ParentPlayer
participant ParentPM
participant ParentCM
participant ChildPM
participant ChildCM
participant ChildPlayer

''''''''''''''''''Paper - Control Events of media object in active Sequence'''''''''''''''''
title Paper - Control Events of media object in active Sequence
activate ParentPlayer
activate ParentCM
== prepare ==
ParentPlayer->ParentCM: prepare( {("height","10%"), ("top","30%")},\n{("evt1ID","media selection","selection"),\n("evt2ID","media presentation","presentation")},\n"file://video.mp4",\n"m1ID" )
activate ChildCM
ParentCM->ChildCM:   prepare(..., ..., ...,"m1ID")
activate ChildPlayer
ChildCM->ChildPlayer:   prepare(..., ..., ...)
== addEvent ==
ParentPlayer->ParentCM: addEvent(("evt3ID","media atribution","atribution"),"m1ID")
ParentCM->ChildCM:   addEvent(...,"m1ID")
ChildCM->ChildPlayer:   addEvent(...)
== removeEvent ==
ParentPlayer->ParentCM: removeEvent(("evt1ID","m1ID")
ParentCM->ChildCM:   removeEvent(("evt1ID","m1ID")
ChildCM->ChildPlayer:   removeEvent(("evt1ID")
== postAction/notifyEventTransition ==
ParentPlayer->ParentCM: postAction("start","evt2ID","m1ID")
ParentCM->ChildCM:   postAction("start","evt2ID","m1ID")
ChildCM->ChildPlayer:   postAction("start","evt2ID")
ChildPlayer->ChildCM:   notifyEventTransition("evt2ID","begins","m1ID")
ChildCM->ParentCM:   notifyEventTransition("evt2ID","begins","m1ID")
ParentCM->ParentPlayer: notifyEventTransition("evt2ID","begins")

''''''''''''''''''Ending PLANTUML params'''''''''''''''''
@enduml