/*----------------------------------------------------------------------
 |   includes
 +---------------------------------------------------------------------*/

#include "fsmda/upnp/upnp_fsmda_utils.h"
#include "NptNetwork.h"
#include "NptTime.h"
#include "PltConstants.h"
#include "PltUPnP.h"
#include "PltUtilities.h"
#include <string>

/*----------------------------------------------------------------------
 |   class fields
 +---------------------------------------------------------------------*/
// singleton fields
PLT_UPnP *UpnpFsmdaUtils::upnp_singleton_ = NULL;
unsigned int UpnpFsmdaUtils::upnp_references_count_ = 0;

// upnp FSMDA Manufacturer constant strings
const char *UpnpFsmdaUtils::kFsmdaManufacturer = "FSMDA";
const char *UpnpFsmdaUtils::kFsmdaManufacturerUrl =
    "http://www.ncl.org.br/fsmda/ondemand";

// parent upnp constant strings
const char *UpnpFsmdaUtils::kParentDeviceType =
    "urn:schemas-upnp-org:device:fsmda-parent-pairing-device:1";
const char *UpnpFsmdaUtils::kParentDeviceFriendlyName = "fsmda parent device";
const char *UpnpFsmdaUtils::kParentDeviceModelName =
    "fsmda-parent-pairing-device model name";
const char *UpnpFsmdaUtils::kParentDeviceModelDescription =
    "fsmda parent device model description";
const char *UpnpFsmdaUtils::kParentDeviceModelUrl =
    "http://www.ncl.org.br/fsmda/fsmda-parent-device";
const char *UpnpFsmdaUtils::kParentDeviceNumber = "1.0";

// child upnp constant strings
const char *UpnpFsmdaUtils::kChildDeviceType =
    "urn:schemas-upnp-org:device:fsmda-child-device:1";
const char *UpnpFsmdaUtils::kChildDeviceFriendlyName = "fsmda child device";
const char *UpnpFsmdaUtils::kChildDeviceModelName =
    "fsmda child device model name";
const char *UpnpFsmdaUtils::kChildDeviceModelDescription =
    "fsmda child device model description";
const char *UpnpFsmdaUtils::kChildDeviceModelUrl =
    "http://www.ncl.org.br/fsmda/fsmda-child-device";
const char *UpnpFsmdaUtils::kChildDeviceModelNumber = "1.0";

// ppm upnp constant strings
const char *UpnpFsmdaUtils::kPpmServiceType =
    "urn:schemas-upnp-org:service:fsmda-parent-pairing:1";
const char *UpnpFsmdaUtils::kPpmServiceId =
    "urn:upnp-org:serviceId:fsmda-parent-pairing";
const char *UpnpFsmdaUtils::kPpmServiceName =
    "urn:upnp-org:serviceId:fsmda-parent-pairing";
const char *UpnpFsmdaUtils::kPpmServiceScpdXml =
    "<?xml version=\"1.0\" ?>"
    "<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">"
    "   <specVersion>"
    "     <major>1</major>"
    "     <minor>0</minor>"
    "   </specVersion>"
    "   <actionList>"
    "     <action>"
    "       <name>AddDeviceToClass</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>application_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_application_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>device_address</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_device_address</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>class_index</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_class_index</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>device_description</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_device_description</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "     <action>"
    "       <name>GetChildIndex</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>application_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_application_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>device_address</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_device_address</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>class_index</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_class_index</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>ret</name>"
    "           <retval />"
    "           <direction>out</direction>"
    "<relatedStateVariable>A_ARG_TYPE_class_index</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "   </actionList>"
    "   <serviceStateTable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_application_id</name>"
    "       <dataType>string</dataType>"
    "       <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_device_address</name>"
    "       <dataType>string</dataType>"
    "       <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_class_index</name>"
    "       <dataType>ui1</dataType>"
    "       <defaultValue>0</defaultValue>"
    "       <allowedValueRange>"
    "         <minimum>0</minimum>"
    "         <maximum>100</maximum>"
    "       </allowedValueRange>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_device_description</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "   </serviceStateTable>"
    "   <intel_nmpr:X_INTEL_NMPR "
    "xmlns:intel_nmpr=\"udn:schemas-intel-com:device-1-0\">2.1</"
    "intel_nmpr:X_INTEL_NMPR>"
    "   <dlna:X_DLNADOC xmlns:dlna=\"udn:schemas-dlna-org:device-1-0\">DMP "
    "1.00</dlna:X_DLNADOC>"
    "</scpd>";

// cpm upnp constant strings
const char *UpnpFsmdaUtils::kCpmServiceType =
    "urn:schemas-upnp-org:service:fsmda-child-pairing:1";
const char *UpnpFsmdaUtils::kCpmServiceId =
    "urn:upnp-org:serviceId:fsmda-child-pairing";
const char *UpnpFsmdaUtils::kCpmServiceName =
    "urn:upnp-org:serviceId:fsmda-child-pairing";
const char *UpnpFsmdaUtils::kCpmServiceScpdXml =
    "<?xml version=\"1.0\" ?>"
    "<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">"
    "   <specVersion>"
    "     <major>1</major>"
    "     <minor>0</minor>"
    "   </specVersion>"
    "   <actionList>"
    "     <action>"
    "       <name>ClassAnnouncement</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>application_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_application_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>class_index</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_class_index</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>class_desc</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_class_desc</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>class_function</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_class_function</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "   </actionList>"
    "   <serviceStateTable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_application_id</name>"
    "       <dataType>string</dataType>"
    "       <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_class_index</name>"
    "       <dataType>ui1</dataType>"
    "       <defaultValue>0</defaultValue>"
    "       <allowedValueRange>"
    "         <minimum>0</minimum>"
    "         <maximum>100</maximum>"
    "       </allowedValueRange>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_class_desc</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_class_function</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "   </serviceStateTable>"
    "   <intel_nmpr:X_INTEL_NMPR "
    "xmlns:intel_nmpr=\"udn:schemas-intel-com:device-1-0\">2.1</"
    "intel_nmpr:X_INTEL_NMPR>"
    "   <dlna:X_DLNADOC xmlns:dlna=\"udn:schemas-dlna-org:device-1-0\">DMP "
    "1.00</dlna:X_DLNADOC>"
    "</scpd>";

// Passive pcm upnp constant strings
const char *UpnpFsmdaUtils::kPassivePcmServiceType =
    "urn:schemas-upnp-org:service:fsmda-passive-parent-communication:1";
const char *UpnpFsmdaUtils::kPassivePcmServiceId =
    "urn:upnp-org:serviceId:fsmda-passive-parent-communication";
const char *UpnpFsmdaUtils::kPassivePcmServiceName =
    "urn:upnp-org:serviceId:fsmda-passive-parent-communication";
const char *UpnpFsmdaUtils::kPassivePcmServiceScpdXml =
    "<?xml version=\"1.0\" ?>"
    "<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">"
    "   <specVersion>"
    "     <major>1</major>"
    "     <minor>0</minor>"
    "   </specVersion>"
    "   <actionList>"
    "     <action>"
    "       <name>NotifyError</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>application_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_application_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>class_index</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_class_index</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>object_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_object_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>message</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_message</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "   </actionList>"
    "   <serviceStateTable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_application_id</name>"
    "       <dataType>string</dataType>"
    "       <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_class_index</name>"
    "       <dataType>ui1</dataType>"
    "       <defaultValue>0</defaultValue>"
    "       <allowedValueRange>"
    "         <minimum>0</minimum>"
    "         <maximum>100</maximum>"
    "       </allowedValueRange>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_object_id</name>"
    "       <dataType>string</dataType>"
    "       <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_message</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "   </serviceStateTable>"
    "   <intel_nmpr:X_INTEL_NMPR "
    "xmlns:intel_nmpr=\"udn:schemas-intel-com:device-1-0\">2.1</"
    "intel_nmpr:X_INTEL_NMPR>"
    "   <dlna:X_DLNADOC xmlns:dlna=\"udn:schemas-dlna-org:device-1-0\">DMP "
    "1.00</dlna:X_DLNADOC>"
    "</scpd>";

// Passive ccm Upnp constant strings
const char *UpnpFsmdaUtils::kPassiveCcmServiceType =
    "urn:schemas-upnp-org:service:fsmda-child-passive-communication:1";
const char *UpnpFsmdaUtils::kPassiveCcmServiceId =
    "urn:upnp-org:serviceId:fsmda-child-passive-communication";
const char *UpnpFsmdaUtils::kPassiveCcmServiceName =
    "urn:upnp-org:serviceId:fsmda-child-passive-communication";
const char *UpnpFsmdaUtils::kPassiveCcmServiceScpdXml =
    "<?xml version=\"1.0\" ?>"
    "<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">"
    "   <specVersion>"
    "     <major>1</major>"
    "     <minor>0</minor>"
    "   </specVersion>"
    "   <actionList>"
    "     <action>"
    "       <name>Prepare</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>position</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_object_id</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "     <action>"
    "       <name>SendContent</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>content</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_content</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "   </actionList>"
    "   <serviceStateTable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_position</name>"
    "       <dataType>string</dataType>"
    "       <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_content</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "   </serviceStateTable>"
    "   <intel_nmpr:X_INTEL_NMPR "
    "xmlns:intel_nmpr=\"udn:schemas-intel-com:device-1-0\">2.1</"
    "intel_nmpr:X_INTEL_NMPR>"
    "   <dlna:X_DLNADOC xmlns:dlna=\"udn:schemas-dlna-org:device-1-0\">DMP "
    "1.00</dlna:X_DLNADOC>"
    "</scpd>";

// active pcm upnp constant strings
const char *UpnpFsmdaUtils::kActivePcmServiceType =
    "urn:schemas-upnp-org:service:fsmda-parent-active-communication:1";
const char *UpnpFsmdaUtils::kActivePcmServiceId =
    "urn:upnp-org:serviceId:fsmda-parent-active-communication";
const char *UpnpFsmdaUtils::kActivePcmServiceName =
    "urn:upnp-org:serviceId:fsmda-parent-active-communication";
const char *UpnpFsmdaUtils::kActivePcmServiceScpdXml =
    "<?xml version=\"1.0\" ?>"
    "<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">"
    "   <specVersion>"
    "     <major>1</major>"
    "     <minor>0</minor>"
    "   </specVersion>"
    "   <actionList>"
    "     <action>"
    "       <name>ReportPropertyValue</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>application_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_application_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>class_index</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_class_index</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>object_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_object_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>name</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_property_name</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>value</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_property_value</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "     <action>"
    "       <name>NotifyEventTransition</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>application_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_application_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>class_index</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_class_index</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>object_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_object_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>transition</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_transition</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "     <action>"
    "       <name>NotifyError</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>application_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_application_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>class_index</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_class_index</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>object_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_object_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>message</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_message</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "   </actionList>"
    "   <serviceStateTable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_application_id</name>"
    "       <dataType>string</dataType>"
    "       <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_class_index</name>"
    "       <dataType>ui1</dataType>"
    "       <defaultValue>0</defaultValue>"
    "       <allowedValueRange>"
    "         <minimum>0</minimum>"
    "         <maximum>100</maximum>"
    "       </allowedValueRange>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_object_id</name>"
    "       <dataType>string</dataType>"
    "       <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_property_name</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_property_value</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_transition</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_message</name>"
    "       <dataType>string</dataType>"
    "       <defaultValue></defaultValue>"
    "     </stateVariable>"
    "   </serviceStateTable>"
    "   <intel_nmpr:X_INTEL_NMPR "
    "xmlns:intel_nmpr=\"udn:schemas-intel-com:device-1-0\">2.1</"
    "intel_nmpr:X_INTEL_NMPR>"
    "   <dlna:X_DLNADOC xmlns:dlna=\"udn:schemas-dlna-org:device-1-0\">DMP "
    "1.00</dlna:X_DLNADOC>"
    "</scpd>";

// active ccm upnp constant strings
const char *UpnpFsmdaUtils::kActiveCcmServiceType =
    "urn:schemas-upnp-org:service:fsmda-child-active-communication:1";
const char *UpnpFsmdaUtils::kActiveCcmServiceId =
    "urn:upnp-org:serviceId:fsmda-child-active-communication";
const char *UpnpFsmdaUtils::kActiveCcmServiceName =
    "urn:upnp-org:serviceId:fsmda-child-active-communication";
const char *UpnpFsmdaUtils::kActiveCcmServiceScpdXml =
    "<?xml version=\"1.0\" ?>"
    "<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">"
    "   <specVersion>"
    "     <major>1</major>"
    "     <minor>0</minor>"
    "   </specVersion>"
    "   <actionList>"
    "     <action>"
    "       <name>Prepare</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>application_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_application_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>class_index</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_class_index</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>object_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_object_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>object_src</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_object_src</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>properties</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_properties</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>events</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_events</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "     <action>"
    "       <name>AddEvent</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>application_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_application_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>class_index</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_class_index</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>object_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_object_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>evt</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_evt</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "     <action>"
    "       <name>RemoveEvent</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>application_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_application_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>class_index</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_class_index</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>object_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_object_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>evt</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_evt_id</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "     <action>"
    "       <name>PostAction</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>application_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_application_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>class_index</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_class_index</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>object_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_object_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>event_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_event_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>action</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_action</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "     <action>"
    "       <name>RequestPropertyValue</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>application_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_application_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>class_index</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_class_index</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>object_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_object_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>property_name</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_property_name</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "     <action>"
    "       <name>SetPropertyValue</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>application_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_application_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>class_index</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_class_index</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>object_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_object_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>property_name</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_property_name</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>property_value</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_property_value</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>property_duration</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_property_duration</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"

    "   </actionList>"
    "   <serviceStateTable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_application_id</name>"
    "       <dataType>string</dataType>"
    "       <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_class_index</name>"
    "       <dataType>ui1</dataType>"
    "       <defaultValue>0</defaultValue>"
    "       <allowedValueRange>"
    "         <minimum>0</minimum>"
    "         <maximum>100</maximum>"
    "       </allowedValueRange>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_object_id</name>"
    "       <dataType>string</dataType>"
    "       <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_object_src</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_properties</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_evt</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_evt_id</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_events</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_event_id</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_action</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_property_name</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_property_value</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_property_duration</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "   </serviceStateTable>"
    "   <intel_nmpr:X_INTEL_NMPR "
    "xmlns:intel_nmpr=\"udn:schemas-intel-com:device-1-0\">2.1</"
    "intel_nmpr:X_INTEL_NMPR>"
    "   <dlna:X_DLNADOC xmlns:dlna=\"udn:schemas-dlna-org:device-1-0\">DMP "
    "1.00</dlna:X_DLNADOC>"
    "</scpd>";

// ondemand pcm upnp constant strings
const char *UpnpFsmdaUtils::kOnDemandPcmServiceType =
    "urn:schemas-upnp-org:service:fsmda-parent-ondemand-communication:1";
const char *UpnpFsmdaUtils::kOnDemandPcmServiceId =
    "urn:upnp-org:serviceId:fsmda-parent-ondemand-communication";
const char *UpnpFsmdaUtils::kOnDemandPcmServiceName =
    "urn:upnp-org:serviceId:fsmda-parent-ondemand-communication"
    "name";
const char *UpnpFsmdaUtils::kOnDemandPcmServiceScpdXml =
    "<?xml version=\"1.0\" ?>"
    "<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">"
    "   <specVersion>"
    "     <major>1</major>"
    "     <minor>0</minor>"
    "   </specVersion>"
    "   <actionList>"
    "     <action>"
    "       <name>NotifyOnDemandContent</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>action</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_content</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>location</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_resource_id</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "   </actionList>"
    "   <serviceStateTable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_action</name>"
    "       <dataType>string</dataType>"
    "       <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_location</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "   </serviceStateTable>"
    "   <intel_nmpr:X_INTEL_NMPR "
    "xmlns:intel_nmpr=\"udn:schemas-intel-com:device-1-0\">2.1</"
    "intel_nmpr:X_INTEL_NMPR>"
    "   <dlna:X_DLNADOC xmlns:dlna=\"udn:schemas-dlna-org:device-1-0\">DMP "
    "1.00</dlna:X_DLNADOC>"
    "</scpd>";

// ondemand ccm upnp constant strings
const char *UpnpFsmdaUtils::kOnDemandCcmServiceType =
    "urn:schemas-upnp-org:service:fsmda-child-ondemand-communication:1";
const char *UpnpFsmdaUtils::kOnDemandCcmServiceId =
    "urn:upnp-org:serviceId:fsmda-child-ondemand-communication";
const char *UpnpFsmdaUtils::kOnDemandCcmServiceName =
    "urn:upnp-org:serviceId:fsmda-child-ondemand-communication";
const char *UpnpFsmdaUtils::kOnDemandCcmServiceScpdXml =
    "<?xml version=\"1.0\" ?>"
    "<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">"
    "   <specVersion>"
    "     <major>1</major>"
    "     <minor>0</minor>"
    "   </specVersion>"
    "   <actionList>"
    "     <action>"
    "       <name>NotifyError</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>object_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_object_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>message</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_message</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "   </actionList>"
    "   <serviceStateTable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_message</name>"
    "       <dataType>string</dataType>"
    "       <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_object_id</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "   </serviceStateTable>"
    "   <intel_nmpr:X_INTEL_NMPR "
    "xmlns:intel_nmpr=\"udn:schemas-intel-com:device-1-0\">2.1</"
    "intel_nmpr:X_INTEL_NMPR>"
    "   <dlna:X_DLNADOC xmlns:dlna=\"udn:schemas-dlna-org:device-1-0\">DMP "
    "1.00</dlna:X_DLNADOC>"
    "</scpd>";

// mediacapture pcm upnp constant strings
const char *UpnpFsmdaUtils::kMediaCapturePcmServiceType =
    "urn:schemas-upnp-org:service:fsmda-parent-mediacapture-communication:1";
const char *UpnpFsmdaUtils::kMediaCapturePcmServiceId =
    "urn:upnp-org:serviceId:fsmda-parent-mediacapture-communication";
const char *UpnpFsmdaUtils::kMediaCapturePcmServiceName =
    "urn:upnp-org:serviceId:fsmda-parent-mediacapture-communication"
    "name";
const char *UpnpFsmdaUtils::kMediaCapturePcmServiceScpdXml =
    "<?xml version=\"1.0\" ?>"
    "<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">"
    "   <specVersion>"
    "     <major>1</major>"
    "     <minor>0</minor>"
    "   </specVersion>"
    "   <actionList>"
    "     <action>"
    "       <name>SendContent</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>content</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_content</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>resource_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_resource_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>child_index</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_child_index</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "   </actionList>"
    "   <serviceStateTable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_content</name>"
    "       <dataType>string</dataType>"
    "       <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "         <name>A_ARG_TYPE_resource_id</name>"
    "         <dataType>string</dataType>"
    "         <defaultValue></defaultValue>"
    "     </stateVariable>"
    "   </serviceStateTable>"
    "   <intel_nmpr:X_INTEL_NMPR "
    "xmlns:intel_nmpr=\"udn:schemas-intel-com:device-1-0\">2.1</"
    "intel_nmpr:X_INTEL_NMPR>"
    "   <dlna:X_DLNADOC xmlns:dlna=\"udn:schemas-dlna-org:device-1-0\">DMP "
    "1.00</dlna:X_DLNADOC>"
    "</scpd>";

// mediacapture ccm upnp constant strings
const char *UpnpFsmdaUtils::kMediaCaptureCcmServiceType =
    "urn:schemas-upnp-org:service:fsmda-child-mediacapture-communication:1";
const char *UpnpFsmdaUtils::kMediaCaptureCcmServiceId =
    "urn:upnp-org:serviceId:fsmda-child-mediacapture-communication";
const char *UpnpFsmdaUtils::kMediaCaptureCcmServiceName =
    "urn:upnp-org:serviceId:fsmda-child-mediacapture-communication"
    "name";
const char *UpnpFsmdaUtils::kMediaCaptureCcmServiceScpdXml =
    "<?xml version=\"1.0\" ?>"
    "<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">"
    "   <specVersion>"
    "     <major>1</major>"
    "     <minor>0</minor>"
    "   </specVersion>"
    "   <actionList>"
    "     <action>"
    "       <name>RequestContent</name>"
    "       <argumentList>"
    "         <argument>"
    "           <name>resource_id</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_resource_id</relatedStateVariable>"
    "         </argument>"
    "         <argument>"
    "           <name>child_index</name>"
    "           <direction>in</direction>"
    "<relatedStateVariable>A_ARG_TYPE_child_index</relatedStateVariable>"
    "         </argument>"
    "       </argumentList>"
    "     </action>"
    "   </actionList>"
    "   <serviceStateTable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_resource_id</name>"
    "       <dataType>string</dataType>"
    "       <defaultValue></defaultValue>"
    "     </stateVariable>"
    "     <stateVariable sendEvents=\"no\">"
    "       <name>A_ARG_TYPE_class_index</name>"
    "       <dataType>ui1</dataType>"
    "       <defaultValue>0</defaultValue>"
    "       <allowedValueRange>"
    "         <minimum>0</minimum>"
    "         <maximum>100</maximum>"
    "       </allowedValueRange>"
    "     </stateVariable>"
    "   </serviceStateTable>"
    "   <intel_nmpr:X_INTEL_NMPR "
    "xmlns:intel_nmpr=\"udn:schemas-intel-com:device-1-0\">2.1</"
    "intel_nmpr:X_INTEL_NMPR>"
    "   <dlna:X_DLNADOC xmlns:dlna=\"udn:schemas-dlna-org:device-1-0\">DMP "
    "1.00</dlna:X_DLNADOC>"
    "</scpd>";

/*----------------------------------------------------------------------
 |   UpnpUtils::GenerateGUID
 +---------------------------------------------------------------------*/
void UpnpFsmdaUtils::GenerateGUID(std::string *guid) {
  NPT_String guid_aux;
  PLT_UPnPMessageHelper::GenerateGUID(guid_aux);
  guid->assign(guid_aux.GetChars());
}

/*----------------------------------------------------------------------
 |   UpnpUtils::RequestUpnpReference
 +---------------------------------------------------------------------*/
PLT_UPnP *UpnpFsmdaUtils::GetRunningInstance() {
  if (UpnpFsmdaUtils::upnp_singleton_ == NULL) {
    // setup Neptune logging
    //    NPT_LogManager::GetDefault().Configure(
    //        "plist:.level=;.handlers=ConsoleHandler;"
    //        ".ConsoleHandler.colors=off;"
    //        ".ConsoleHandler.filter=42");
    NPT_LogManager::GetDefault().Configure(
        "plist:.level=;.handlers=;platinum.level=;platinum.handlers=");

    PLT_Constants::GetInstance().SetDefaultDeviceLease(NPT_TimeInterval(60.));
    //    PLT_Constants::GetInstance().SetDefaultSubscribeLease(
    //        NPT_TimeInterval(20.));
    //    PLT_Constants::GetInstance().SetAnnounceMulticastTimeToLive(0.5);
    //    PLT_Constants::GetInstance().SetSearchMulticastTimeToLive(0.5);
    NPT_List<NPT_IpAddress> list;
    PLT_UPnPMessageHelper::GetIPAddresses(list);
    UpnpFsmdaUtils::upnp_singleton_ = new PLT_UPnP();
    //    UpnpFsmdaUtils::upnp_singleton_->SetIgnoreLocalUUIDs(false);
    UpnpFsmdaUtils::upnp_singleton_->Start();
    UpnpFsmdaUtils::upnp_references_count_ = 0;
  }
  UpnpFsmdaUtils::upnp_references_count_++;
  return UpnpFsmdaUtils::upnp_singleton_;
}

/*----------------------------------------------------------------------
 |   UpnpUtils::ReleaseUpnpReference
 +---------------------------------------------------------------------*/
void UpnpFsmdaUtils::ReleaseInstance() {
  if (UpnpFsmdaUtils::upnp_references_count_ == 0) {
    return;
  } else if (UpnpFsmdaUtils::upnp_references_count_ == 1) {
    UpnpFsmdaUtils::upnp_singleton_->Stop();
    delete upnp_singleton_;
    UpnpFsmdaUtils::upnp_singleton_ = NULL;
    UpnpFsmdaUtils::upnp_references_count_ = 0;
  } else {
    UpnpFsmdaUtils::upnp_references_count_--;
  }
}

/*----------------------------------------------------------------------
 |   UpnpUtils::IsUpnpRunning
 +---------------------------------------------------------------------*/
bool UpnpFsmdaUtils::IsUpnpStarted() {
  if (UpnpFsmdaUtils::upnp_singleton_ == NULL) {
    return false;
  } else {
    UpnpFsmdaUtils::upnp_singleton_->IsRunning();
  }
}
